# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for the FUSE filesystem.
#

obj-$(CONFIG_VIRTIO_FS) := virtiofs.o
virtiofs-y := dev.o inode.o dir.o file.o xattr.o acl.o readdir.o ioctl.o iomode.o virtio_fs.o

