#!/bin/bash -x

DEST_DIR=$1

# is systemd supported and systemctl exists
if (systemctl 2>/dev/null | grep -qw "\\-\.mount" 2>/dev/null); then
	install -d ${DEST_DIR}/lib/systemd/system
	install -d ${DEST_DIR}/etc/systemd/system
	install -m 0644 ofed_scripts/openibd.service ${DEST_DIR}/lib/systemd/system
	install -m 0644 ofed_scripts/mlnx_interface_mgr\@.service  ${DEST_DIR}/etc/systemd/system
	echo 'DRIVERS=="*mlx*", SUBSYSTEM=="net", ACTION=="add",RUN+="/bin/systemctl --no-block start mlnx_interface_mgr@$env{INTERFACE}.service"' >> ${DEST_DIR}/etc/udev/rules.d/90-ib.rules
else
	# no systemd support
	echo 'DRIVERS=="*mlx*", SUBSYSTEM=="net", ACTION=="add", RUN+="/bin/mlnx_interface_mgr.sh $env{INTERFACE} <&- >/dev/null 2>&1 &"' >> ${DEST_DIR}/etc/udev/rules.d/90-ib.rules
fi
