#!/bin/sh

arch=$(uname -m)
base_dir="/usr/src/ofa_kernel/$arch"
if ! ls "$base_dir/"dkms_moved_* >/dev/null 2>&1; then
	exit 0
fi

dir=`ls -d "$base_dir/"dkms_moved_* | head -n1`
dir_name=${dir##*/}
kvers=${dir_name#dkms_moved_}
if [ ! -d "$base_dir/$kvers" ]; then
	# FIXME: Currently verbose. Remov ebefore final merge (also: -v of mv)
	echo "Undoing devel files move of mlnx-ofa_kernel-dkms:"
	mv -v "$dir" "$base_dir/$kvers"
fi
