#ifndef COMPAT_FIX_H
#define COMPAT_FIX_H

#include "../../compat/config.h"

#ifdef CONFIG_MLX5_ESWITCH
#ifdef CONFIG_COMPAT_CLS_FLOWER_MOD
#define HAVE_TC_FLOWER_OFFLOAD	1
#define HAVE_TC_CLSFLOWER_STATS	1
#endif

#ifdef CONFIG_COMPAT_TCF_TUNNEL_KEY_MOD
#define HAVE_NET_TC_ACT_TC_TUNNEL_KEY_H 1
#define HAVE_TCF_TUNNEL_INFO 1
#endif

#ifdef CONFIG_COMPAT_TCF_VLAN_MOD
#define HAVE_IS_TCF_VLAN 1
#endif
#else /* CONFIG_MLX5_ESWITCH */
#undef CONFIG_COMPAT_IP_TUNNELS
#undef CONFIG_COMPAT_TCF_GACT
#undef CONFIG_COMPAT_FLOW_DISSECTOR
#undef CONFIG_COMPAT_CLS_FLOWER_MOD
#undef CONFIG_COMPAT_TCF_TUNNEL_KEY_MOD
#undef CONFIG_COMPAT_TCF_VLAN_MOD
#endif

#ifdef CONFIG_COMPAT_TCF_PEDIT_MOD
#define HAVE_TCF_PEDIT_TCFP_KEYS_EX 1
#endif

#if defined(HAVE_TC_CLS_OFFLOAD_HANDLE) && defined(CONFIG_COMPAT_RHEL_JD)
#define CONFIG_COMPAT_SKIP_OFFLOAD_HANDLE 1
#endif

#endif /* COMPAT_FIX_H */
