/* SPDX-License-Identifier: GPL-2.0 */
#ifndef COMPAT_CONST_H
#define COMPAT_CONST_H

/* Include the autogenerated header file */
#include "../../compat/config.h"

#include_next <linux/const.h>

#ifndef UL
#define UL(x)           (_UL(x))
#endif

#ifndef ULL
#define ULL(x)          (_ULL(x))
#endif

#endif /* COMPAT_CONST_H */
