#ifndef COMPAT_DEVICE_H
#define COMPAT_DEVICE_H

#include_next <linux/device.h>

/* Include the autogenerated header file */
#include "../../compat/config.h"

#ifndef dev_warn_ratelimited
#define dev_warn_ratelimited(dev, fmt, ...)
#endif

#endif /* COMPAT_DEVICE_H */
