#ifndef _COMPAT_LINUX_FS_H
#define _COMPAT_LINUX_FS_H

/* Include the autogenerated header file */
#include "../../compat/config.h"

#include_next <linux/fs.h>

#if !defined(CONFIG_COMPAT) || !defined(HAVE_COMPAT_PTR_IOCTL_EXPORTED) 
#define compat_ptr_ioctl NULL
#else
extern long compat_ptr_ioctl(struct file *file, unsigned int cmd,
		                                        unsigned long arg);
#endif /*CONFIG_COMPAT*/

#endif /* _COMPAT_LINUX_FS_H */
