#ifndef _COMPAT_LINUX_INTERRUPT_H
#define _COMPAT_LINUX_INTERRUPT_H

#include_next<linux/interrupt.h>

/* Include the autogenerated header file */
#include "../../compat/config.h"


#endif /* _COMPAT_LINUX_INTERRUPT_H */
