#ifndef _COMPAT_LINUX_LIST_H
#define _COMPAT_LINUX_LIST_H

/* Include the autogenerated header file */
#include "../../compat/config.h"

#include_next <linux/list.h>



#ifndef HAVE_LIST_ENTRY_IS_HEAD
#define list_entry_is_head(pos, head, member)                          \
               (&pos->member == (head))
#endif

#endif /* _COMPAT_LINUX_LIST_H */
