# SPDX-License-Identifier: GPL-2.0-only
GCOV_PROFILE := $(CONFIG_MLX5_GCOV)
obj-$(CONFIG_INFINIBAND)		+= core/
obj-$(CONFIG_INFINIBAND)		+= hw/
obj-$(CONFIG_INFINIBAND)		+= ulp/
obj-$(CONFIG_INFINIBAND)		+= sw/
