obj-m += mlx_compat.o
#compat-objs :=

mlx_compat-y += main.o

mlx_compat-y += output_core.o
mlx_compat-y += interval_tree.o

mlx_compat-y += pci.o
mlx_compat-y += mmu_notifier.o
mlx_compat-y += xarray.o
mlx_compat-y += rdma_dim.o
mlx_compat-y += dim.o
mlx_compat-y += net_dim.o
mlx_compat-y += file.o
ifdef CONFIG_MLX5_CLS_ACT
mlx_compat-y += flow_offload.o
mlx_compat-y += cls_api.o
endif

ifdef CONFIG_MLX5_MACSEC
mlx_compat-y += macsec.o
endif
