/* SPDX-License-Identifier: GPL-2.0 OR Linux-OpenIB */
/* Copyright (c) 2025 NVIDIA Corporation & Affiliates */

#ifndef MLX5_DEVM_DRIVER_PARAMS_H
#define MLX5_DEVM_DRIVER_PARAMS_H

enum mlx5_devm_param_id {
	MLX5_DEVM_PARAM_ID_BASE = MLXDEVM_PARAM_GENERIC_ID_MAX,
	MLX5_DEVM_PARAM_ID_CPU_AFFINITY,
	MLX5_DEVM_PARAM_ID_CMPL_EQ_DEPTH,
	MLX5_DEVM_PARAM_ID_ASYNC_EQ_DEPTH,
	MLX5_DEVM_PARAM_ID_DISABLE_ROCE,
	MLX5_DEVM_PARAM_ID_DISABLE_FC,
	MLX5_DEVM_PARAM_ID_DISABLE_NETDEV,
	MLX5_DEVM_PARAM_ID_MAX_CMPL_EQS,
};

#endif
