# SPDX-License-Identifier: GPL-2.0-only

# Commented out as should be compiled only in backports
# Allow compilation on base kernel as VFIO not supported on 6.0
# Backports will remove the comment .
# Backport shpould be removed in next version

#obj-$(CONFIG_MLX5_VFIO_PCI) += mlx5-vfio-pci.o
#mlx5-vfio-pci-y := main.o cmd.o

