/* SPDX-License-Identifier: GPL-2.0 */
#ifndef _COMPAT_VDSO_CONST_H
#define _COMPAT_VDSO_CONST_H

/* Include the autogenerated header file */
#include "../../compat/config.h"

#include_next <vdso/const.h>

#ifndef UL
#define UL(x)           (_UL(x))
#endif

#ifndef ULL
#define ULL(x)          (_ULL(x))
#endif

#endif /* _COMPAT_VDSO_CONST_H */
